### ISSUE TITLE
How to Pretrain on our own documents

### ISSUE THREAD

**Issue by aged-dragon** [jpWang/LiLT#10]
Let's say I have 1000s of domain specific documents in English. How can I Pretrain them on top of roberta-en + Lilt Based existing checkpoint.

**Comment by jpWang** [comment]
Hi,
Maybe you can refer to [Test-Time Adaptation for Visual Document Understanding](https://arxiv.org/abs/2206.07240).

**Comment by vibeeshan025** [comment]
I wanted to know In your code how you have achieved this. I can see your example for FUNDS and how fine tuning is done. But I am not sure how the OCR Texts of FUNDS are used and added to the LILT base before doing the fine-tuning. Or is that something not required at all.

May be I am missing out something. Please help me understand
