### ISSUE TITLE
The difference of results on the SER of FUNSD between the Table 2 and the Table 6 in the paper.

### ISSUE THREAD

**Issue by WenjinW** [jpWang/LiLT#15]
Hi!
I like the idea of decoupling text and layout information to leverage existing pre-trained language models.
I had some confusion when I was reading the paper.
- Table 2 shows that the F1 of LiLT[InfoXLM] on the SER task of FUNSD is 0.8586.
![image](https://user-images.githubusercontent.com/30342227/185411265-bd15b55d-77ed-4e6c-a840-0309a7f1b95d.png)
- However, in Table 6, the F1 is 0.8415.
![image](https://user-images.githubusercontent.com/30342227/185411794-2f5a9557-4af7-451b-9bd5-f294201d1a42.png)

Why are the performances reported in the two tables different?

Thanks for your reply.

**Comment by leitouran** [comment]
Hi, I had the same confusion but I think the results you mention for Table 2 are for the multilingual model, while the ones in Table 3 are English only.

**Comment by jpWang** [comment]
Hi, @WenjinW @leitouran  ,
Table 2 follows the fine-tune style of https://github.com/microsoft/unilm/blob/master/layoutlmft/examples/run_funsd.py, but Table 3 follows the fine-tune style of https://github.com/microsoft/unilm/blob/master/layoutlmft/examples/run_xfun_ser.py.
