### ISSUE TITLE
Recommendations for inference and further fine-tuning

### ISSUE THREAD

**Issue by leitouran** [jpWang/LiLT#16]
Hi,

Just got my XFUND-ES finetuning job to work! While I wait, I am trying to work my way through the code to create an inference script. Would running the run_xfun_ser.py script with `--do_predict` (and passing the checkpoint I obtained by finetuning) suffice? Also, if I wanted to create my own dataset to finetune further, would you recommend a transfer learning approach starting from this XFUND fine-tuned checkpoint or should I go straight to create the custom dataset?

Thank you very much in advance. This is great work!

**Comment by jpWang** [comment]
Hi,
(1) Yes. You can write what you want to do under https://github.com/jpWang/LiLT/blob/main/examples/run_xfun_ser.py#L268.
(2) I think you can go straight to create your own custom dataset.
