### ISSUE TITLE
HuggingFace version

### ISSUE THREAD

**Issue by ManuelFay** [jpWang/LiLT#2]
Hello, amazing job ! 

I love the paradigm of decoupling the LM and the Layout model at first, before fine-tuning with joint training !  I've managed to port my LayoutXLM code to your framework almost plug and play, and was wondering if you were planning to open an official model implementation on the HuggingFace transformers library ?
As is, except for a few tweaks due to version changes, and perhaps a processor object wrapping the tokenizer not much is required, so I was wondering if you had plans to do so ?
Cheers and again, great work !
Best,
Manuel

**Comment by jpWang** [comment]
Hi Manuel,
thanks for your attention and recognition of our work.
So far, we don't have an urgent plan to do it. However, if this work gets more attention, or after we further improve this research, we will put it on the agenda.

**Comment by bilelomrani1** [comment]
That would be awesome! Looking forward to hearing more about your research.

**Comment by jpWang** [comment]
@ManuelFay Hi Manuel,
Recently I noticed that you have successfully made our LiLT models available on HuggingFace (For example, https://huggingface.co/manu/lilt-infoxlm-base). Thanks for your kind help and efforts ! 😃

**Comment by vibeeshan025** [comment]
Any Idea of simple inference code for using the fine-tuned model.

**Comment by NielsRogge** [comment]
Hi folks (cc @jpWang),

Happy to share that I've got a working HuggingFace implementation. I'm able to reproduce the results (F1 of 88% on FUNSD). The model is here: https://huggingface.co/nielsr/lilt-roberta-en-base-finetuned-funsd

I'll open a PR soon :)

**Comment by vishal-nayak1** [comment]
@NielsRogge (cc @jpWang) Hi, Are you planning to add this model to transformer library?It would be really great full.

**Comment by jpWang** [comment]
> Hi folks (cc @jpWang),
> 
> Happy to share that I've got a working HuggingFace implementation. I'm able to reproduce the results (F1 of 88% on FUNSD). The model is here: https://huggingface.co/nielsr/lilt-roberta-en-base-finetuned-funsd
> 
> I'll open a PR soon :)

Hi, 
thanks for your great effort. Contact me if any problem encountered :)

**Comment by NielsRogge** [comment]
Hi @jpWang,

I've opened a PR here to add LiLT to 🤗 Transformers: https://github.com/huggingface/transformers/pull/19450.

Would you like to create an organization for the company/research institute you're part of, such that we transfer the weigths there?

**Comment by jpWang** [comment]
> Hi @jpWang,
> 
> I've opened a PR here to add LiLT to 🤗 Transformers: [huggingface/transformers#19450](https://github.com/huggingface/transformers/pull/19450).
> 
> Would you like to create an organization for the company/research institute you're part of, such that we transfer the weigths there?

Hi @NielsRogge ,
I have joined the organization of our Lab: https://github.com/SCUT-DLVCLab. Is this ok? :)

**Comment by NielsRogge** [comment]
Hi,

What's the URL of the HuggingFace organization? I can't seem to find SCUT-DLVCLab on [hf.co](https://huggingface.co/).

**Comment by jpWang** [comment]
Hi, I just created our organization: https://huggingface.co/SCUT-DLVCLab.

**Comment by NielsRogge** [comment]
Thanks a lot! Now 2 checkpoints are transferred there.

Could you give me your email address, such that I can set up a Slack channel? I'd like to discuss some things related to LiLT.

**Comment by jpWang** [comment]
My email is scutjpwang@foxmail.com. Thanks for your effort :)

**Comment by jpWang** [comment]
Hi folks，
Happy to share that LiLT has been added to HuggingFace/transformers library~!
Thank @NielsRogge for his great efforts~!

**Comment by jpWang** [comment]
Hi folks，
Happy to share that LiLT has been added to HuggingFace/transformers library：https://huggingface.co/docs/transformers/main/en/model_doc/lilt !
Thank @NielsRogge for his great efforts!
