### ISSUE TITLE
large checkpoint 

### ISSUE THREAD

**Issue by saetlan** [jpWang/LiLT#24]
Hello, 
Thanks for making the code available !

I was wondering if there was a lilt-only-large checkpoint available or a way to easily generate it ? 
I would like to try to combine lilt with a large xlm Roberta to see the potential gain between base and large.

Thanks !

**Comment by jpWang** [comment]
Hi,
due to the limitation of computing resources, we haven't trained the large LiLT model yet. It is considered for future work.

**Comment by logan-markewich** [comment]
+1 for training LiLT-Large 👍🏻
