### ISSUE TITLE
post custom dataset training ser on funsd model, inference issue

### ISSUE THREAD

**Issue by wrathrope** [jpWang/LiLT#31]
any tips for inference script, Actually I am new to this, I am able to train a model on custom dataset using script funsd.
but not able to load model using transformers Autotokenclassifer

any help will be appreciated

![image](https://user-images.githubusercontent.com/120730734/208114097-6c00e562-2eb4-46af-8415-3ff01b87be2d.png)

**Comment by logan-markewich** [comment]
try using the absolute path (right click on folder, copy full path). I think it is failing to find your checkpoint dir and then trying to load from huggingface hub
