### ISSUE TITLE
not able to reproduce results

### ISSUE THREAD

**Issue by sujit420** [jpWang/LiLT#4]
First of all, thanks for this nice work.
However, I am unable to reproduce the results given in the table. I was training Funsd for relation extraction task.
Please let me know if I am doing anything wrong.
python examples/run_xfun_re.py --model_name_or_path lilt-infoxlm-base --tokenizer_name xlm-roberta-base --output_dir ls_re_xfund_lilt-infoxlm-base  --do_train --do_eval --lang en --max_steps 20000 --per_device_train_batch_size 2 --warmup_ratio 0.1
I am getting eval f1 of 0.47

**Comment by jpWang** [comment]
Hi,
thanks for your feedback. Since my GPUs are being occupied by other experiments, I will soon check the performance of RE task in a few days.

**Comment by jpWang** [comment]
@sujit420 The fine-tune strategy of RE task has been updated. You can try the newest codes and command lines.

**Comment by sujit420** [comment]
> @sujit420 The fine-tune strategy of RE task has been updated. You can try the newest codes and command lines.

Thanks, @jpWang for the quick response. Though I am yet to get the reported score of 0.6276 in RE for funsd data. But I am able to get 0.606 eval f1 which is reasonable.
Also, I would like to know the process to get results reported for multi-task fine-tuning on funsd/xfund? Thanks in advance.

**Comment by jpWang** [comment]
For multi-task fine-tuning, you can simply expand `max_steps` by as many times as the number of languages (=8 for FUNSD+XFUND). You can refer to https://github.com/jpWang/LiLT#multi-task-relation-extraction-on-xfund.

**Comment by vibeeshan025** [comment]
Hi, Both of you guys, how long it took you to run this process, what's the setup used.
