### ISSUE TITLE
pre-processed data

### ISSUE THREAD

**Issue by minhoooo1** [jpWang/LiLT#41]
非常感谢你们的开源工作，非常有趣的是我本科和硕士导师都是来自华工的。回归正题，我无法下载在OneDrive中的预处理数据，不知道你们能提供其他的获取方式吗？比如谷歌云盘，或者麻烦你们发我邮箱1121851272@qq.com，感谢了！

**Comment by coder4nlp** [comment]
pre-processed dat +1

**Comment by jpWang** [comment]
Hi,
sorry for the late response. I have just tested all OneDrive links and they are still available. You may need to use tools like VPN to access the links.
