### ISSUE TITLE
"linking" in Dataset and IOB Tagging

### ISSUE THREAD

**Issue by vibeeshan025** [jpWang/LiLT#8]
The `en.train.json`  contains a linking filed array. Is it required for SER ( Semantic Entity Recognition instead of RE) tasks? 

Have you ever tried IOB tagging for multiple word outputs?

**Comment by jpWang** [comment]
1. No.
2. This repo follows LayoutLM family's style. You can feel free to use IOB tagging + CRF. Generally, it can further improve performance.
